version: "3.9"

services:
  django:
    build:
      context: .
      dockerfile: docker/django/local/Dockerfile
    volumes:
      - .:/home/django/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=ssh_application
      - POSTGRES_USER=diploma_user
      - POSTGRES_PASSWORD=password
      - DB_HOST=database
      - CELERY_RESULT_BACKEND=redis://redis:6379
      - CELERY_BROKER_URL=pyamqp://rabbitmq:5672
    env_file:
      - .env.local
    depends_on:
      database:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      redis:
        condition: service_started
  database:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ssh_application
      - POSTGRES_USER=diploma_user
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d ssh_application -U diploma_user']
      interval: 2s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.12

  redis:
    image: redis:7.2

volumes:
  postgres_data:
